-- IRONCORE REAL MEMBERSHIP DATABASE
-- Run this entire file in Supabase SQL Editor.

create table if not exists public.profiles (
    id uuid primary key references auth.users(id) on delete cascade,
    full_name text not null,
    email text,
    role text not null default 'member' check (role in ('member','admin')),
    created_at timestamptz not null default now()
);

create table if not exists public.memberships (
    id bigint generated by default as identity primary key,
    user_id uuid not null unique references public.profiles(id) on delete cascade,
    plan text not null check (plan in ('Starter','Performance','Elite')),
    price numeric(10,2) not null,
    status text not null default 'pending' check (status in ('pending','active','expired','cancelled')),
    start_date date,
    end_date date,
    created_at timestamptz not null default now()
);

alter table public.profiles enable row level security;
alter table public.memberships enable row level security;

-- Profiles: a member can read/update only their own profile.
create policy "Members can view own profile"
on public.profiles for select
using (auth.uid() = id);

create policy "Members can create own profile"
on public.profiles for insert
with check (auth.uid() = id);

create policy "Members can update own profile"
on public.profiles for update
using (auth.uid() = id)
with check (auth.uid() = id);

-- Memberships: a member can read and create/update only their own membership.
create policy "Members can view own membership"
on public.memberships for select
using (auth.uid() = user_id);

create policy "Members can create own membership"
on public.memberships for insert
with check (auth.uid() = user_id);

create policy "Members can update own membership"
on public.memberships for update
using (auth.uid() = user_id)
with check (auth.uid() = user_id);

-- Optional: make one account an admin manually after signup.
-- Replace USER_UUID with the user's auth UUID, then run:
-- update public.profiles set role = 'admin' where id = 'USER_UUID';
